### ISSUE TITLE
Combine Mendelian Families search - AttributeError 'NoneType' - mongo_datastore.py, line 99, in get_variants

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/xbrowse#126]
```
[Sun Mar 01 21:13:04 2015] [error] Traceback (most recent call last):
[Sun Mar 01 21:13:04 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
[Sun Mar 01 21:13:04 2015] [error]     response = callback(request, *callback_args, **callback_kwargs)
[Sun Mar 01 21:13:04 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
[Sun Mar 01 21:13:04 2015] [error]     return view_func(*args, **kwargs)
[Sun Mar 01 21:13:04 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 25, in _wrapped_view
[Sun Mar 01 21:13:04 2015] [error]     return view_func(request, *args, **kwargs)
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse_server/decorators.py", line 37, in wrapper
[Sun Mar 01 21:13:04 2015] [error]     return f(request, *args, **kwargs)
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse_server/api/views.py", line 529, in combine_mendelian_families
[Sun Mar 01 21:13:04 2015] [error]     genes = api_utils.calculate_combine_mendelian_families(family_group, search_spec)
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse_server/api/utils.py", line 382, in calculate_combine_mendelian_families
[Sun Mar 01 21:13:04 2015] [error]     search_spec.genotype_quality_filter,
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse/analysis_modules/combine_mendelian_families.py", line 46, in get_families_by_gene
[Sun Mar 01 21:13:04 2015] [error]     quality_filter
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse/variant_search/family.py", line 206, in get_variants_with_inheritance_mode
[Sun Mar 01 21:13:04 2015] [error]     for variant in INHERITANCE_FUNCTIONS[inheritance_mode](mall.variant_store, mall.reference, family, variant_filter, quality_filter):
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse/variant_search/family.py", line 84, in get_homozygous_recessive_variants
[Sun Mar 01 21:13:04 2015] [error]     indivs_to_consider=family.indiv_id_list(),
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse/variant_search/family.py", line 46, in get_variants
[Sun Mar 01 21:13:04 2015] [error]     variant_filter=variant_filter
[Sun Mar 01 21:13:04 2015] [error]   File "/srv/xbrowse/xbrowse/datastore/mongo_datastore.py", line 99, in get_variants
[Sun Mar 01 21:13:04 2015] [error]     for variant_dict in collection.find(db_query).sort('xpos'):
[Sun Mar 01 21:13:04 2015] [error] AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by bw2** [comment]
This issue could be fixed by re-enabling Celery tasks, or by having the server-side code launch a background process that loads the variants, or by implementing some simplified home-made version of Celery with a constantly-running daemon that does the loading. I'm leaning towards solution 2 since it avoids needing a separate background process.
